const colors = {
  dark: {
    text: '#F0F0F0',
    tint: '#FF6B2C',
    background: '#0D0D0D',
    foreground: '#F0F0F0',
    card: '#1C1C1E',
    cardForeground: '#F0F0F0',
    primary: '#FF6B2C',
    primaryForeground: '#FFFFFF',
    secondary: '#252525',
    secondaryForeground: '#F0F0F0',
    muted: '#2A2A2A',
    mutedForeground: '#888888',
    accent: '#FF8C42',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#2A2A2A',
    input: '#2A2A2A',
  },
  light: {
    text: '#1A1A1A',
    tint: '#FF6B2C',
    background: '#F5F5F5',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    primary: '#FF6B2C',
    primaryForeground: '#FFFFFF',
    secondary: '#F0F0F0',
    secondaryForeground: '#1a1a1a',
    muted: '#EBEBEB',
    mutedForeground: '#737373',
    accent: '#FF8C42',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#E5E5E5',
    input: '#E5E5E5',
  },
  radius: 16,
};

export default colors;
